[options]
admin_passwd = admin
db_host = localhost
db_port = 5432
db_user = cyclex
db_password = cyclex
addons_path = /media/sabry3/sabry_backup/cycle_x/odoo18/addons,/media/sabry3/sabry_backup/cycle_x/enterprise_18,/media/sabry3/sabry_backup/cycle_x,/media/sabry3/sabry_backup/cycle_x/custom_addons
xmlrpc_port = 10018