[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = tests
addopts = 
    -v
    --tb=short
    --strict-markers
    --ignore=../models
    --ignore=../controllers
markers =
    slow: marks tests as slow
    api: marks tests that require API connection
    ui: marks tests for UI only

